#!/bin/bash

# Name of the tmux session
SESSION_NAME="monitoring"

# Check if the session already exists
tmux has-session -t $SESSION_NAME 2>/dev/null

if [ $? != 0 ]; then

  # Create a new session and run htop in the first pane
  tmux new-session -d -s $SESSION_NAME -n monitor 'htop'

  # Split the window vertically and run nvtop in the second pane
  tmux split-window -v -t $SESSION_NAME:1 'nvtop'

  # Select the first pane
  # tmux select-pane -t $SESSION_NAME:0.0

fi

# Attach to the session
tmux attach -t $SESSION_NAME
